# Generated by Django 2.1 on 2018-09-02 19:26

from django.db import migrations


def forwards(apps, schema_editor):
    TestModel = apps.get_model('ddv_example', 'TestModel')
    data = (
        ('first', 'description 1'),
        ('second', 'description 2'),
        ('third', 'description 3'),
        ('some other', 'description 4'),
    )
    for name, description in data:
        TestModel.objects.create(name=name, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('ddv_example', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
