# Generated by Django 2.1 on 2019-12-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddv_example', '0002_auto_20180902_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='first',
            field=models.CharField(default='default value', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='last',
            field=models.CharField(default='default last', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='mid',
            field=models.CharField(default='default mid', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='passw',
            field=models.CharField(default='default pass', max_length=10),
            preserve_default=False,
        ),
    ]
