# Generated by Django 2.1 on 2019-12-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddv_example', '0004_auto_20191225_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='first',
            field=models.CharField(max_length=10, verbose_name='first'),
        ),
    ]
