# Generated by Django 2.2.7 on 2019-11-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=10)),
                ('last', models.CharField(max_length=10)),
                ('mid', models.CharField(max_length=10)),
                ('passw', models.CharField(max_length=10)),
            ],
        ),
    ]
